### ISSUE TITLE
serf animations not working when using FSStudio exported data

### ISSUE THREAD

**Issue by tlongstretch** [freeserf/fsstudio#17]
I was able to start a game using the FSStudio exported data of a SPAE data file.   The game starts fine and the Map objects all look correct, but the serf animations are not right.  The serfs are only partial torso and jerky moving around the map.  I am not sure if this is an incomplete feature of Freeserf itself or an issue with FSStudio, or windows, or SPAE...

**Comment by tlongstretch** [comment]
Thank you.  The animations are smooth now - no longer jerky, but the serf heads and torsos are still not lined up correctly.   

![image](https://i.imgur.com/bbHk23X.png)

Ignore the trees, I am playing with snow/winter graphics.

**Comment by wdigger** [comment]
@tlongstretch What scale do you use when exporting resources?

**Comment by tlongstretch** [comment]
I am using the default of '1', as I do not know what this setting is used for I have not tried changing it
